### ISSUE TITLE
Définir les données à utiliser dans Synthea

### ISSUE THREAD

**Issue by lgfquentin** [ysayad/medical-dashboard#45]
Dans Synthea, je veux savoir quels topics regarder afin de bien récupérer les bonnes données pour être en capacité d'écrire toutes les données correctement dans la base de données sans qu'il manque une information.

**Comment by soufiane-ezzemany** [comment]
![Image](https://github.com/ysayad/medical-dashboard/assets/76752758/29e3c64c-d062-4726-b26a-cb47d5a2ed7f)

Voici le résultat après reflexion
